Update README.md
astronomer/deploy-action pull request #3
Opened 2023-01-17 15:59 UTC by kwcanuck

As requested by Paola, completed a review of the README content.

2023-01-17 16:24 UTC, kwcanuck commented on README.md
> +The following is the workflow for the custom GitHub Deploy Action:
```suggestion
The following is the workflow for Deploy Action:
```

2023-01-17 16:27 UTC, kwcanuck commented on README.md
> +Deploy Action is intended to be used with [Deployment API keys](https://docs.astronomer.io/astro/api-keys). To use Deploy Action, you need to set the `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` e
```suggestion
Deploy Action is intended to be used with [Deployment API keys](https://docs.astronomer.io/astro/api-keys). To use Deploy Action, you need to set the `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` environment variables in your GitHub Actions workflow. The environment variables define how to log in to Astro and what Deployment to deploy changes to. Astronomer recommends using GitHub Actions secrets to set the environment variables. An example workflow script is provided in ** Deploy code example**. 
```

2023-01-17 16:31 UTC, kwcanuck commented on README.md
> +Deploy Action is intended to be used with [Deployment API keys](https://docs.astronomer.io/astro/api-keys). To use Deploy Action, you need to set the `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` e
```suggestion
Deploy Action is intended to be used with [Deployment API keys](https://docs.astronomer.io/astro/api-keys). To use Deploy Action, you need to set the `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` environment variables in your GitHub Actions workflow. Astronomer recommends using GitHub Actions secrets to set the environment variables. An example workflow script is provided in ** Deploy code example**. 
```

2023-01-18 12:53 UTC, kwcanuck commented on README.md
> +Deploy Action is intended to be used with [Deployment API keys](https://docs.astronomer.io/astro/api-keys). To use Deploy Action, you need to set the `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` e
```suggestion
Deploy Action is intended to be used with [Deployment API keys](https://docs.astronomer.io/astro/api-keys). To use Deploy Action, you need to set the `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` environment variables in your GitHub Actions workflow. Astronomer recommends using GitHub Actions secrets to set the environment variables. An example workflow script is provided in **Deploy code example**. 
```

2023-01-18 14:14 UTC, kwcanuck commented on README.md
> +The following example shows how to use Deploy Action to deploy your code to an Astro Deployment whenever code is pushed to the main branch of your projects repository. The `ASTRONOMER_KEY_ID` and `AS
```suggestion
The following example shows how to use Deploy Action to deploy your code to an Astro Deployment whenever code is pushed to the main branch of your projects repository. The `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` environment variable values are defined by your [Deployment API key](https://docs.astronomer.io/astro/api-keys).
```

2023-01-23 17:55 UTC, jwitz reviewed
I updated this based on some patterns I identified in other major GitHub Action READMEs

2023-01-23 17:55 UTC, jwitz commented on README.md
> +# Deploy Action
```suggestion
# Deploy to Astro
```
Looking at the [GitHub Marketplace](https://github.com/marketplace?category=deployment&query=sort%3Apopularity-desc&type=actions&verification=), this seems to be the most common naming format for Deployment actions.

2023-01-23 17:55 UTC, jwitz commented on README.md
> +You use Deploy Action to create CI/CD pipelines that automate the deployment of code changes to a Deployment. For more information about Astro CI/CD workflows, see [Automate code deploys with CI/CD](
```suggestion 
This action deploys code from your GitHub repository to an Astro Deployment. It runs whenever you commit to your repository's main branch. For more information about Astro CI/CD workflows, see [Automate code deploys with CI/CD](https://docs.astronomer.io/astro/ci-cd).
```

2023-01-23 17:55 UTC, jwitz commented on README.md
> +Deploy Action should only be used in a GitHub Actions workflow that runs when code is merged into a `main` or an equivalent branch. You can use the Deploy Action with DAG-only deploys activated or de
```suggestion
This action can be used only to deploy code from `main` or an equivalent branch. To configure a CI/CD pipeline for multiple branches, see [Astronomer documentation](https://docs.astronomer.io/astro/ci-cd?tab=multiple%20branch#github-actions-dag-based-deploy). 

You can use the Deploy Action with DAG-only deploys activated or deactivated. When DAG-only deploys are activated, the action does not rebuild and deploy your image when your commit only includes changes to the `/dags` folder. For more information about DAG-only deploys, see [Deploy DAGs only](https://docs.astronomer.io/astro/deploy-code#deploy-dags-only).
```

2023-01-23 17:55 UTC, jwitz commented on README.md
> +The following is the workflow for Deploy Action:
```suggestion
The action completes the following steps whenever you commit to your main branch:

```

2023-01-23 17:55 UTC, jwitz commented on README.md
> +- Your `dags/` folder is deployed to your Deployment if you changed files inside the `/dags` folder
```suggestion
- Check out your repository.
- Check whether your commit only changed DAG code.
- Optional. Test DAG code with pytest.
- If the commit included only changes to DAG code, push the change to Astro without building a new project image.
- If the change included changes to project configurations, rebuild your project image and deploy it to Astro.
```

2023-01-23 17:55 UTC, jwitz commented on README.md
> +- Your `dags/` folder is deployed to your Deployment if you changed files inside the `/dags` folder
Removed the passive language here, as I think we can be explicit that the action does all of this stuff.

2023-01-23 17:55 UTC, jwitz commented on README.md
> +Deploy Action is intended to be used with [Deployment API keys](https://docs.astronomer.io/astro/api-keys). To use Deploy Action, you need to set the `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` e
```suggestion
To use the action, you must set the `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` environment variables in your GitHub Actions workflow to the Key ID and secret for an existing [Deployment API key](https://docs.astronomer.io/astro/api-keys). Astronomer recommends using GitHub Actions secrets to set these environment variables. An example workflow script is provided in **Workflow file example**. 
```

2023-01-23 17:55 UTC, jwitz commented on README.md
> +| `force` | `false` | When set to `true`, your code is force deployed without testing or parsing
```suggestion
| `pytest-file` | (all tests run) | Specifies the custom pytest files to run with the pytest command. For example, you could specify `/tests/test-tags.py`|
| `force` | `false` | When set to `true`, your code is force deployed without testing or parsing |
```

2023-01-23 17:55 UTC, jwitz commented on README.md
> +## Deploy code example
```suggestion
## Workflow file examples
```

2023-01-23 17:55 UTC, jwitz commented on README.md
> +The following example shows how to use Deploy Action to deploy your code to an Astro Deployment whenever code is pushed to the main branch of your projects repository. The `ASTRONOMER_KEY_ID` and `AS
```suggestion
```

2023-01-23 17:55 UTC, jwitz commented on README.md
> +The following example shows how to use Deploy Action to deploy your code to an Astro Deployment whenever code is pushed to the main branch of your projects repository. The `ASTRONOMER_KEY_ID` and `AS
This is duplicative with the definition of the action itself, plus the information that we include earlier. I think it's pretty self explanatory.

2023-01-23 17:55 UTC, jwitz commented on README.md
> +In the following example, DAG-only deploys are enabled and DAG files are parsed in both image and DAG deploys.
```suggestion
In the following example, DAG-only deploys are enabled and DAG files are parsed for both image and DAG deploys.
```

2023-01-23 17:55 UTC, jwitz commented on README.md
> +### Change the DAG folder
```suggestion

Use the following topics to further configure the action based on your needs.

### Change the DAG folder
```

2023-01-23 17:58 UTC, jwitz commented
@sunkickr can't add you for review to this PR but please take a look and let us know what you think!

2023-02-02 13:42 UTC, kwcanuck commented on README.md
> +- Check out your repository.
```suggestion
- Checks out your repository.
```

2023-02-02 13:43 UTC, kwcanuck commented on README.md
> +- Check whether your commit only changed DAG code.
```suggestion
- Checks whether your commit only changed DAG code.
```

2023-02-02 13:43 UTC, kwcanuck commented on README.md
> +- Optional. Test DAG code with pytest.
```suggestion
- Optional. Tests DAG code with pytest.
```

2023-02-02 13:43 UTC, kwcanuck commented on README.md
> +- If the commit included only changes to DAG code, push the change to Astro without building a new project image.
```suggestion
- If the commit included only changes to DAG code, pushes the change to Astro without building a new project image.
```

2023-02-02 13:44 UTC, kwcanuck commented on README.md
> +- If the change included changes to project configurations, rebuild your project image and deploy it to Astro.
```suggestion
- If the change included changes to project configurations, rebuilds your project image and deploys it to Astro.
```

2023-02-02 13:46 UTC, kwcanuck commented on README.md
> +To use the action, you must set the `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` environment variables in your GitHub Actions workflow to the Key ID and secret for an existing [Deployment API key]
```suggestion
To use the action, you must set the `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET` environment variables in your GitHub Actions workflow to the Key ID and secret for an existing [Deployment API key](https://docs.astronomer.io/astro/api-keys). Astronomer recommends using GitHub Actions secrets to set these environment variables. An example workflow script is provided in **Workflow file examples**. 
```

2023-02-02 17:29 UTC, sunkickr requested changes
mainly just think we should clarify that the action is branch setup agnostic. Meaning it doesn't automatically deploy when a user merges code into main. Users have to set that up in their workflow file. The action can be used in any scenario the user can think of

2023-02-02 17:29 UTC, sunkickr commented on README.md
> +This action deploys code from your GitHub repository to an Astro Deployment. It runs whenever you commit to your repository's main branch. For more information about Astro CI/CD workflows, see [Autom
It doesn't necessarily run whenever you commit to your repository's main branch. This is up to how you set up your workflow

2023-02-02 17:29 UTC, sunkickr commented on README.md
> +This action can be used only to deploy code from `main` or an equivalent branch. To configure a CI/CD pipeline for multiple branches, see [Astronomer documentation](https://docs.astronomer.io/astro/c
```suggestion
This action can be used only to deploy code to deploy code to Astro Deployments. This README contains exmaples on how to use it to deploy code when changes are made to a main branch. To configure a CI/CD pipeline for multiple branches, see [Astronomer documentation](https://docs.astronomer.io/astro/ci-cd?tab=multiple%20branch#github-actions-dag-based-deploy). 
```

2023-02-02 17:29 UTC, sunkickr commented on README.md
> +In the following example, DAG-only deploys are enabled and DAG files are parsed for both image and DAG deploys.
code is pushed from a main branch only if the workflow file here is used. This does not happen automatically by the action. maybe we should say something about this here?

2023-02-02 19:51 UTC, kwcanuck commented on README.md
> +This action can be used only to deploy code to deploy code to Astro Deployments. This README contains exmaples on how to use it to deploy code when changes are made to a main branch. To configure a C
```suggestion
This action can only be used to deploy code to Astro Deployments. This README includes examples of how you can use the action to deploy code when changes are made to a main branch. To configure a CI/CD pipeline for multiple branches, see [Astronomer documentation](https://docs.astronomer.io/astro/ci-cd?tab=multiple%20branch#github-actions-dag-based-deploy). 
```

2023-02-02 19:52 UTC, kwcanuck commented on README.md
> +In the following example, DAG-only deploys are enabled and DAG files are parsed for both image and DAG deploys.
```suggestion
In the following example, DAG-only deploys are enabled and DAG files are parsed for both image and DAG deploys. Code is only pushed from a main branch when the workflow file is used.
```

2023-02-02 20:18 UTC, sunkickr commented on README.md
> +The action completes the following steps whenever you commit to your main branch:
```suggestion
The action completes the following steps whenever your CI/CD pipeline is triggered:
```

2023-02-02 20:20 UTC, sunkickr commented on README.md
> +In the following example, DAG-only deploys are enabled and DAG files are parsed for both image and DAG deploys. Code is only pushed from a main branch when the workflow file is used.
```suggestion
In the following example, DAG-only deploys are enabled and DAG files are parsed for both image and DAG deploys. This workflow example deploys code when it is pushed into the main branch.
```

2023-02-02 21:57 UTC, paolaperaza approved these changes

2023-02-02 23:16 UTC, paolaperaza commented on README.md
> +This action deploys code from your GitHub repository to an Astro Deployment. It runs as a step within a github workflow file. For more information about Astro CI/CD workflows, see [Automate code depl
@sunkickr I sort of re-wrote this intro... I just want to make sure that:

- We're taking the space to define Astro as a product, and at least point folks in the right direction to learn more
- Make benefits of this action clear, especially for Airflow users who don't use Astro (I suspect more of those users will land here)
- Makes prerequisites clear
- Be clear about "how to use this" in the context of our docs

2023-02-03 14:14 UTC, kwcanuck commented on README.md
> +This action deploys code from your GitHub repository to an Astro Deployment. It runs as a step within a github workflow file. For more information about Astro CI/CD workflows, see [Automate code depl
@paolaperaza I noticed the following issues with your new copy:

![image](https://user-images.githubusercontent.com/104205257/216623009-7e2b66e8-148d-41f1-aec5-aad6dea0444d.png)
 
This should be updated to: _Automate code deployment to Astro when you merge changes to a branch in your repository_.

![image](https://user-images.githubusercontent.com/104205257/216623822-07188b82-1317-4462-889c-10196a299fc5.png)

This text should be updated to: _Runs `astro deploy --dags` if the commit includes DAG code changes_ and _Runs `astro deploy` if the commit includes project configuration changes_

![image](https://user-images.githubusercontent.com/104205257/216624739-5738434d-9712-4f0f-936d-7ba3eb4e2dfa.png)

The convention appears to be _GitHub Actions secrets_. See [GitHub Actions Secrets](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28).

![image](https://user-images.githubusercontent.com/104205257/216625161-800131c7-72ed-4a75-b425-eac33f0175b2.png)

![image](https://user-images.githubusercontent.com/104205257/216625208-e9d60108-aaf9-49fa-935f-4dc7264f125c.png)

2023-02-03 16:49 UTC, sunkickr approved these changes

2023-02-03 21:08 UTC, kwcanuck commented
Wondering where my feedback from earlier today went. They seem to have disappeared.

2023-02-06 15:38 UTC, paolaperaza reviewed
Couple more comments to clean this up, @sunkickr. Wanna take a look and merge?

2023-02-06 15:38 UTC, paolaperaza commented on README.md
> +| `image-name` |  | Specifies a custom, locally built image to deploy |
```suggestion
| `image-name` |  | Specifies a custom, locally built Docker image to deploy |
```

2023-02-06 15:38 UTC, paolaperaza commented on README.md
> +In the following example, DAG-only deploys are enabled and DAG files are parsed for both image and DAG deploys. This workflow example deploys code when it is pushed into the main branch.
```suggestion
In the following example, the GitHub action deploys code to Astro with DAG-only deploys enabled. This example assumes that you have one Astro Deployment and one branch. When a change is merged to the `main` branch, your Astro project is deployed to Astro. DAG files are parsed on every deploy and no pytests are ran.
```

2023-02-06 15:38 UTC, paolaperaza commented on README.md
> +In the following example, the pytest located at `/tests/test-tags.py` runs before the image is deployed.
```suggestion
In the following example, the pytest located at `/tests/test-tags.py` runs before deploying to Astro.
```

2023-02-06 15:38 UTC, paolaperaza commented on README.md
> +In the following example, the parse and pytests are skipped.
```suggestion
In the following example, `force` is enabled and both the DAG parse and pytest processes are skipped.
```

2023-02-06 15:38 UTC, paolaperaza commented on README.md
> +### Use a custom image
```suggestion
### Deploy a custom Docker image
```

2023-02-06 15:38 UTC, paolaperaza commented on README.md
> +In the following example, a custom image is built and deployed to an Astro Deployment.
```suggestion
In the following example, a custom Docker image is built and deployed to an Astro Deployment.
```

2023-02-06 20:45 UTC, merged